In [1]:
# Import dependencies

import pandas as pd
import numpy as np
from path import Path
from sqlalchemy import create_engine
from config import db_password


# Import Austin_Animal_Center_Intakes_08312021.csv and read into DataFrame

file_path = Path("Resources/Austin_Animal_Center_Intakes_08312021.csv")
intakes_df = pd.read_csv(file_path)
intakes_df.head()

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A786884,*Brock,1/3/2019 16:19,1/3/2019 16:19,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,7/5/2015 12:59,7/5/2015 12:59,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,4/14/2016 18:43,4/14/2016 18:43,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
3,A665644,NaN,10/21/2013 7:59,10/21/2013 7:59,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico
4,A682524,Rio,6/29/2014 10:38,6/29/2014 10:38,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray

In [2]:
# Rename column headers in intakes file to Python naming conventions

intakes_df_renamed = intakes_df.rename(columns={"Animal ID": "animal_id",
                            "Name": "animal_name",
                            "DateTime": "intake_date",
                            "MonthYear": "intake_date_2",
                            "Found Location": "found_location",
                            "Intake Type": "intake_type",
                            "Intake Condition": "intake_condition",
                            "Animal Type": "animal_type",
                            "Sex upon Intake": "sex_upon_intake",
                            "Age upon Intake": "age_upon_intake",
                            "Breed": "breed",
                            "Color": "color"}, inplace = False)
intakes_df_renamed

,animal_id,animal_name,intake_date,intake_date_2,found_location,intake_type,intake_condition,animal_type,sex_upon_intake,age_upon_intake,breed,color
0,A786884,*Brock,1/3/2019 16:19,1/3/2019 16:19,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,7/5/2015 12:59,7/5/2015 12:59,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,4/14/2016 18:43,4/14/2016 18:43,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
3,A665644,NaN,10/21/2013 7:59,10/21/2013 7:59,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico
4,A682524,Rio,6/29/2014 10:38,6/29/2014 10:38,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray
...,...,...,...,...,...,...,...,...,...,...,...,...
130612,A841094,A841094,8/20/2021 12:13,8/20/2021 12:13,3800 North Ih 35 in Austin (TX),Stray,Normal,Cat,Intact Male,3 months,Domestic Shorthair,Brown Tabby
130613,A841101,Sharpe,8/20/2021 12:51,8/20/2021 12:51,Austin (TX),Owner Surrender,Normal,Cat,Intact Female,1 year,Domestic Shorthair,Tortie
130614,A840120,*Lentil,8/2/2021 17:36,8/2/2021 17:36,5517 Icon Street in Austin (TX),Stray,Normal,Other,Intact Female,2 years,Rabbit Sh,Black/White
130615,A840648,*Carob,8/11/2021 16:35,8/11/2021 16:35,Austin (TX),Owner Surrender,Normal,Other,Intact Male,1 year,Rabbit Sh,Gray
130616,A840650,*Sprout,8/11/2021 16:35,8/11/2021 16:35,Austin (TX),Owner Surrender,Normal,Other,Intact Female,1 year,Rabbit Sh,Gray/White

In [3]:
# Drop all instances of duplicate animal_id in intakes file

cleaned_intakes_df = intakes_df_renamed.drop_duplicates(subset=['animal_id'], keep=False)
cleaned_intakes_df

,animal_id,animal_name,intake_date,intake_date_2,found_location,intake_type,intake_condition,animal_type,sex_upon_intake,age_upon_intake,breed,color
0,A786884,*Brock,1/3/2019 16:19,1/3/2019 16:19,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,7/5/2015 12:59,7/5/2015 12:59,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,4/14/2016 18:43,4/14/2016 18:43,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
3,A665644,NaN,10/21/2013 7:59,10/21/2013 7:59,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico
4,A682524,Rio,6/29/2014 10:38,6/29/2014 10:38,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray
...,...,...,...,...,...,...,...,...,...,...,...,...
130612,A841094,A841094,8/20/2021 12:13,8/20/2021 12:13,3800 North Ih 35 in Austin (TX),Stray,Normal,Cat,Intact Male,3 months,Domestic Shorthair,Brown Tabby
130613,A841101,Sharpe,8/20/2021 12:51,8/20/2021 12:51,Austin (TX),Owner Surrender,Normal,Cat,Intact Female,1 year,Domestic Shorthair,Tortie
130614,A840120,*Lentil,8/2/2021 17:36,8/2/2021 17:36,5517 Icon Street in Austin (TX),Stray,Normal,Other,Intact Female,2 years,Rabbit Sh,Black/White
130615,A840648,*Carob,8/11/2021 16:35,8/11/2021 16:35,Austin (TX),Owner Surrender,Normal,Other,Intact Male,1 year,Rabbit Sh,Gray
130616,A840650,*Sprout,8/11/2021 16:35,8/11/2021 16:35,Austin (TX),Owner Surrender,Normal,Other,Intact Female,1 year,Rabbit Sh,Gray/White

In [4]:
# Import Austin_Animal_Center_Outcomes_08312021.csv and read into DataFrame

file_path = Path("Resources/Austin_Animal_Center_Outcomes_08312021.csv")
outcomes_df = pd.read_csv(file_path)
outcomes_df.head()

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A794011,Chunk,5/8/2019 18:20,5/8/2019 18:20,5/2/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
1,A776359,Gizmo,7/18/2018 16:02,7/18/2018 16:02,7/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
2,A821648,NaN,8/16/2020 11:38,8/16/2020 11:38,8/16/2019,Euthanasia,NaN,Other,Unknown,1 year,Raccoon,Gray
3,A720371,Moose,2/13/2016 17:59,2/13/2016 17:59,10/8/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff
4,A674754,NaN,3/18/2014 11:47,3/18/2014 11:47,3/12/2014,Transfer,Partner,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby

In [5]:
# Rename column headers in outcomes file to Python naming conventions

outcomes_df_renamed = outcomes_df.rename(columns={"Animal ID": "animal_id",
                            "Name": "animal_name",
                            "DateTime": "outcome_date",
                            "MonthYear": "outcome_date_2",
                            "Date of Birth": "date_of_birth",
                            "Outcome Type": "outcome_type",
                            "Outcome Subtype": "outcome_subtype",
                            "Animal Type": "animal_type",
                            "Sex upon Outcome": "sex_upon_outcome",
                            "Age upon Outcome": "age_upon_outcome",
                            "Breed": "breed",
                            "Color": "color"}, inplace = False)
outcomes_df_renamed

,animal_id,animal_name,outcome_date,outcome_date_2,date_of_birth,outcome_type,outcome_subtype,animal_type,sex_upon_outcome,age_upon_outcome,breed,color
0,A794011,Chunk,5/8/2019 18:20,5/8/2019 18:20,5/2/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
1,A776359,Gizmo,7/18/2018 16:02,7/18/2018 16:02,7/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
2,A821648,NaN,8/16/2020 11:38,8/16/2020 11:38,8/16/2019,Euthanasia,NaN,Other,Unknown,1 year,Raccoon,Gray
3,A720371,Moose,2/13/2016 17:59,2/13/2016 17:59,10/8/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff
4,A674754,NaN,3/18/2014 11:47,3/18/2014 11:47,3/12/2014,Transfer,Partner,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby
...,...,...,...,...,...,...,...,...,...,...,...,...
130642,A841450,A841450,8/31/2021 12:33,8/31/2021 12:33,8/5/2021,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Longhair,Black
130643,A841560,Eli,8/31/2021 12:17,8/31/2021 12:17,3/30/2017,Return to Owner,Field,Dog,Neutered Male,4 years,Labrador Retriever,Black
130644,A841582,217G,8/31/2021 12:30,8/31/2021 12:30,8/8/2021,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair,Black
130645,A841599,NaN,8/31/2021 12:31,8/31/2021 12:31,8/21/2021,Transfer,Partner,Cat,Intact Female,1 weeks,Domestic Shorthair,Blue Tabby
130646,A841581,182G,8/31/2021 12:31,8/31/2021 12:31,8/8/2021,Transfer,Partner,Cat,Intact Female,3 weeks,Domestic Shorthair,Calico

In [6]:
# Drop all instances of duplicate animal_id in outcomes file

cleaned_outcomes_df = outcomes_df_renamed.drop_duplicates(subset=['animal_id'], keep=False)
cleaned_outcomes_df

,animal_id,animal_name,outcome_date,outcome_date_2,date_of_birth,outcome_type,outcome_subtype,animal_type,sex_upon_outcome,age_upon_outcome,breed,color
0,A794011,Chunk,5/8/2019 18:20,5/8/2019 18:20,5/2/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
1,A776359,Gizmo,7/18/2018 16:02,7/18/2018 16:02,7/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
2,A821648,NaN,8/16/2020 11:38,8/16/2020 11:38,8/16/2019,Euthanasia,NaN,Other,Unknown,1 year,Raccoon,Gray
4,A674754,NaN,3/18/2014 11:47,3/18/2014 11:47,3/12/2014,Transfer,Partner,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby
6,A814515,Quentin,5/6/2020 7:59,5/6/2020 7:59,3/1/2018,Adoption,Foster,Dog,Neutered Male,2 years,American Foxhound/Labrador Retriever,White/Brown
...,...,...,...,...,...,...,...,...,...,...,...,...
130642,A841450,A841450,8/31/2021 12:33,8/31/2021 12:33,8/5/2021,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Longhair,Black
130643,A841560,Eli,8/31/2021 12:17,8/31/2021 12:17,3/30/2017,Return to Owner,Field,Dog,Neutered Male,4 years,Labrador Retriever,Black
130644,A841582,217G,8/31/2021 12:30,8/31/2021 12:30,8/8/2021,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair,Black
130645,A841599,NaN,8/31/2021 12:31,8/31/2021 12:31,8/21/2021,Transfer,Partner,Cat,Intact Female,1 weeks,Domestic Shorthair,Blue Tabby
130646,A841581,182G,8/31/2021 12:31,8/31/2021 12:31,8/8/2021,Transfer,Partner,Cat,Intact Female,3 weeks,Domestic Shorthair,Calico

In [7]:
# Save cleaned intakes and outcomes files into Resources folder

cleaned_intakes_df.to_csv('Resources/intakes.csv', index=False)
cleaned_outcomes_df.to_csv('Resources/outcomes.csv', index=False)

In [8]:
# Import cleaned intakes and outcomes DataFrames into PostgreSQL database

db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/Austin_AniML_Rescue"

engine = create_engine(db_string)

cleaned_intakes_df.to_sql(name='intakes', con=engine, if_exists='replace')
cleaned_outcomes_df.to_sql(name='outcomes', con=engine, if_exists='replace')