In [2]:
# Import intakes_outcomes table from PostgreSQL database to machine learning model

import pandas as pd
from sqlalchemy import create_engine
from config import db_password

db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/Austin_AniML_Rescue"

engine = create_engine(db_string)

query = "SELECT * FROM intakes_outcomes"

raw_df = pd.read_sql(query, con=engine, columns=["animal_id", "animal_type", "breed", "color", "intake_type", "date_of_birth",
                                                "intake_date", "intake_condition", "sex_upon_intake", "age_upon_intake",
                                                "outcome_date", "outcome_type", "outcome_subtype", "sex_upon_outcome",
                                                "age_upon_outcome"])

raw_df

,animal_id,animal_type,breed,color,intake_type,date_of_birth,intake_date,intake_condition,sex_upon_intake,age_upon_intake,outcome_date,outcome_type,outcome_subtype,sex_upon_outcome,age_upon_outcome
0,A047759,Dog,Dachshund,Tricolor,Owner Surrender,4/2/2004,4/2/2014 15:55,Normal,Neutered Male,10 years,4/7/2014 15:12,Transfer,Partner,Neutered Male,10 years
1,A134067,Dog,Shetland Sheepdog,Brown/White,Public Assist,10/16/1997,11/16/2013 9:02,Injured,Neutered Male,16 years,11/16/2013 11:54,Return to Owner,None,Neutered Male,16 years
2,A141142,Dog,Labrador Retriever/Pit Bull,Black/White,Stray,6/1/1998,11/16/2013 14:46,Aged,Spayed Female,15 years,11/17/2013 11:40,Return to Owner,None,Spayed Female,15 years
3,A163459,Dog,Miniature Schnauzer Mix,Black/Gray,Stray,10/19/1999,11/14/2014 15:11,Normal,Intact Female,15 years,11/14/2014 19:28,Return to Owner,None,Intact Female,15 years
4,A165752,Dog,Lhasa Apso Mix,Brown/White,Stray,8/18/1999,9/15/2014 11:28,Normal,Neutered Male,15 years,9/15/2014 16:35,Return to Owner,None,Neutered Male,15 years
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105362,A841599,Cat,Domestic Shorthair,Blue Tabby,Stray,8/21/2021,8/30/2021 14:52,Neonatal,Intact Female,1 weeks,8/31/2021 12:31,Transfer,Partner,Intact Female,1 weeks
105363,A841600,Cat,Domestic Shorthair,Blue Tabby,Stray,8/21/2021,8/30/2021 14:52,Neonatal,Intact Male,1 weeks,8/31/2021 12:32,Transfer,Partner,Intact Male,1 weeks
105364,A841601,Cat,Domestic Shorthair,Black,Stray,8/21/2021,8/30/2021 14:52,Neonatal,Intact Female,1 weeks,8/31/2021 12:32,Transfer,Partner,Intact Female,1 weeks
105365,A841603,Cat,Domestic Shorthair,Brown Tabby,Stray,8/21/2021,8/30/2021 14:52,Neonatal,Intact Female,1 weeks,8/31/2021 12:32,Transfer,Partner,Intact Female,1 weeks
105366,A841622,Cat,Domestic Shorthair,Black/Black,Stray,8/30/2019,8/30/2021 20:40,Injured,Intact Male,2 years,8/31/2021 9:48,Euthanasia,Rabies Risk,Intact Male,2 years